# version: '3.8'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: node-app
#     ports:
#       - "3000:3000"  # Expose port 3000 to the host
#     environment:
#       - NODE_ENV=development
#       - DB_HOST=postgres
#       - DB_PORT=5432
#       - DB_USER=postgres_user
#       - DB_PASSWORD=postgres_password
#       - DB_NAME=postgres_db
#     depends_on:
#       - postgres
#     networks:
#       - app-network

#   postgres:
#     image: postgres:14
#     container_name: postgres-db
#     environment:
#       POSTGRES_USER: postgres_user
#       POSTGRES_PASSWORD: postgres_password
#       POSTGRES_DB: postgres_db
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"  # Expose PostgreSQL on port 5432
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge

# volumes:
#   pgdata:
#     driver: local
