name: CI Pipeline

on:
  push:
    branches:
      - '**'  # Trigger for pushes on any branch
  pull_request:
    branches:
      - production
      - develop

jobs:
  # Job 1: Build the application
  build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.build.outputs.image-tag }}  # Pass image tag to the push-image job

    steps:
      - uses: actions/checkout@v3

      # Build the Docker image
      - name: Build Docker image
        id: build
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          docker build -t banking:${IMAGE_TAG} .
          echo "image-tag=${IMAGE_TAG}" >> $GITHUB_ENV  # Store IMAGE_TAG in environment
        outputs:
          image-tag: ${{ steps.build.outputs.image-tag }}  # Output the IMAGE_TAG

  # Job 2: Push Docker image
  push-image:
    runs-on: ubuntu-latest
    needs: build  # Ensure 'build' job runs first

    steps:
      - uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push Docker image using the same IMAGE_TAG
      - name: Push Docker image
        run: |
          IMAGE_TAG=${{ needs.build.outputs.image-tag }}  # Retrieve IMAGE_TAG from build job
          
          # Check if IMAGE_TAG is not empty
          if [[ -z "$IMAGE_TAG" ]]; then
            echo "Error: IMAGE_TAG is empty!"
            exit 1
          fi

          docker tag banking:${IMAGE_TAG} phat99/banking:${IMAGE_TAG}
          docker push phat99/banking:${IMAGE_TAG}
