name: CI Pipeline

on:
  push:
    branches:
      - '**'  # Trigger for pushes on any branch
  pull_request:
    branches:
      - production
      - develop

jobs:
  # Job 1: Build the application and Docker image
  build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.build.outputs.image-tag }}  # Pass image-tag as an output from this job

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3


  # Job 2: Push Docker image
  push-image:
    runs-on: ubuntu-latest
    needs: build  # Ensure 'build' job runs first

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Push Docker image using the same IMAGE_TAG from the build job
      - name: Push Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          docker build -t banking:${IMAGE_TAG} .
          docker tag banking:${IMAGE_TAG} phat99/banking:${IMAGE_TAG}
          docker push phat99/banking:${IMAGE_TAG}
