name: CI Pipeline

on:
  push:
    branches:
      - '**'  # Trigger for pushes on any branch
  pull_request:
    branches:
      - production
      - develop

jobs:
  # Job 1: Build the application
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Build Docker image
      - name: Build Docker image
        id: build
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          docker build -t banking:${IMAGE_TAG} .
          echo "image-tag=${IMAGE_TAG}" >> $GITHUB_ENV  # Store IMAGE_TAG in environment
          echo "::set-output name=image-tag::${IMAGE_TAG}"  # Set IMAGE_TAG as output

  # Job 2: Push Docker image
  push-image:
    runs-on: ubuntu-latest
    needs: build  # Ensure the 'build' job runs first

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored as GitHub secret
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password stored as GitHub secret

      # Step 3: Push Docker image using the same IMAGE_TAG
      - name: Push Docker image
        run: |
          IMAGE_TAG=${{ needs.build.outputs.image-tag }}  # Retrieve the IMAGE_TAG from the build job

          # Check if IMAGE_TAG is not empty
          if [[ -z "$IMAGE_TAG" ]]; then
            echo "Error: IMAGE_TAG is empty!"
            exit 1
          fi

          docker tag banking:${IMAGE_TAG} phat99/banking:${IMAGE_TAG}
          docker push phat99/banking:${IMAGE_TAG}
